[package]
name = "rstrobes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
fxhash = "0.2.1"
log = "0.4.20"
rayon = "1.7.0"
sigpipe = "0.1.3"
xxhash-rust = { version = "0.8.5", features = ["xxh64"] }

[profile.release]
debug = true
