[package]
name = "py-rstrobes"
version = "0.0.0"
edition = "2021"

[lib]
name = "rstrobes"
crate-type = ["cdylib"]

[dependencies]
rstrobes = { path = ".." }
pyo3 = { version = "0.21.0-beta.0", features = ["extension-module"] }
